### ISSUE TITLE
请求报告有问题

### ISSUE THREAD

**Issue by SylvieManx** [penghaiping/amazon-sp-api#1]
![image](https://user-images.githubusercontent.com/20614254/113085765-091f1d00-9213-11eb-9e6b-18b282d69c04.png)
![image](https://user-images.githubusercontent.com/20614254/113085776-0e7c6780-9213-11eb-9c6d-f36038dc5d94.png)
![image](https://user-images.githubusercontent.com/20614254/113085818-2227ce00-9213-11eb-85e3-7a83190f202e.png)
![image](https://user-images.githubusercontent.com/20614254/113086086-8f3b6380-9213-11eb-94ad-bd8e1820ccfa.png)
请求不到报告数据

**Comment by penghaiping** [comment]
这类业务数据问题请询问amazon mws 或sp-api团队，我这里只是个sdk，如果遇到sdk使用问题可以在这里提issue
