### ISSUE TITLE
If i want use vendor-direct,I should use swagger-codegen to generate client?

### ISSUE THREAD

**Issue by GOODBOY008** [penghaiping/amazon-sp-api#5]
If i want use vendor-direct,I should use swagger-codegen to generate client?

**Comment by penghaiping** [comment]
Yes，use the model json file that start with ”vendor“ at https://github.com/amzn/selling-partner-api-models/tree/main/models   to generate.

**Comment by GOODBOY008** [comment]
Thank you for your reply, this project has code generator templets?

**Comment by penghaiping** [comment]
> Thank you for your reply, this project has code generator templets?

unfortunately, this project do not have, but you can find templates from [here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#generating-a-java-sdk-with-lwa-token-exchange-and-authentication)
